import { randomUUID } from 'node:crypto';
import bcrypt from 'bcryptjs';
import cookieParser from 'cookie-parser';
import cors from 'cors';
import express, { type Request } from 'express';
import helmet from 'helmet';
import { z } from 'zod';
import type { CampaignStatus, Role } from '@coupon/shared';
import { config, corsOrigins } from './config.js';
import { databaseFile, db, type Campaign } from './db/store.js';
import { BedrockService } from './integrations/bedrock.js';
import { allowRoles, authenticate, createRefreshToken, hashToken, signAccessToken } from './lib/auth.js';
import { AppError, asyncHandler, errorHandler, notFoundHandler, ok, pageArgs, paginated, sanitize } from './lib/http.js';
import { logger } from './lib/logger.js';

const app=express(), bedrock=new BedrockService();
app.disable('x-powered-by'); app.use(helmet()); app.use(cors({origin:corsOrigins,credentials:true})); app.use(express.json({limit:'1mb'})); app.use(cookieParser());
app.use((req,res,next)=>{req.id=String(req.headers['x-request-id']??randomUUID());res.setHeader('X-Request-ID',String(req.id));const started=Date.now();res.on('finish',()=>logger.info({requestId:String(req.id),method:req.method,path:req.path,status:res.statusCode,durationMs:Date.now()-started},'request'));next();});
const pageSchema=z.object({page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)});
const dtoUser=(u:{id:string;username:string;displayName:string;role:Role})=>({id:u.id,username:u.username,displayName:u.displayName,role:u.role});
const paginate=<T>(res:express.Response,items:T[],query:{page:number;pageSize:number})=>{const p=pageArgs(query);return paginated(res,items.slice(p.skip,p.skip+p.pageSize),p.page,p.pageSize,items.length);};
async function audit(req:Request,action:string,outcome:string,resourceType?:string,resourceId?:string,detail:unknown={}){await db.write(s=>{s.auditLogs.unshift({id:db.id(),requestId:String(req.id),actorId:req.auth?.userId,action,outcome,resourceType,resourceId,detail:sanitize(detail),createdAt:new Date().toISOString()});});}
const requireItem=<T>(item:T|undefined,code:string,message:string):T=>{if(!item)throw new AppError(404,code,message);return item;};

app.get('/api/v1/health',asyncHandler(async(_req,res)=>{await db.ready;return ok(res,{status:'ok',database:'json-file',databaseFile,ai:'optional',timestamp:new Date().toISOString()});}));

app.post('/api/v1/auth/login',asyncHandler(async(req,res)=>{const input=z.object({username:z.string().min(1),password:z.string().min(1)}).parse(req.body);const user=await db.read(s=>s.users.find(u=>u.username===input.username));if(!user||!await bcrypt.compare(input.password,user.passwordHash)){await audit(req,'auth.login','failure',undefined,undefined,{username:input.username});throw new AppError(401,'AUTH_INVALID_CREDENTIALS','用户名或密码错误');}req.auth={userId:user.id,username:user.username,role:user.role};const refresh=createRefreshToken();await db.write(s=>s.refreshTokens.push({id:db.id(),userId:user.id,tokenHash:refresh.hash,expiresAt:new Date(Date.now()+config.REFRESH_TOKEN_TTL_DAYS*86400000).toISOString(),createdAt:new Date().toISOString()}));res.cookie(config.COOKIE_NAME,refresh.raw,{httpOnly:true,sameSite:'lax',secure:config.NODE_ENV==='production',path:'/api/v1/auth',maxAge:config.REFRESH_TOKEN_TTL_DAYS*86400000});await audit(req,'auth.login','success','user',user.id);return ok(res,{accessToken:signAccessToken({sub:user.id,username:user.username,role:user.role}),expiresIn:config.ACCESS_TOKEN_TTL_SECONDS,user:dtoUser(user)},'登录成功');}));
app.post('/api/v1/auth/refresh',asyncHandler(async(req,res)=>{const raw=req.cookies?.[config.COOKIE_NAME] as string|undefined;if(!raw)throw new AppError(401,'AUTH_REFRESH_INVALID','刷新令牌无效');const next=createRefreshToken();const user=await db.write(s=>{const current=s.refreshTokens.find(t=>t.tokenHash===hashToken(raw));if(!current||current.revokedAt||new Date(current.expiresAt)<=new Date())throw new AppError(401,'AUTH_REFRESH_INVALID','刷新令牌无效或已撤销');const user=requireItem(s.users.find(u=>u.id===current.userId),'AUTH_REFRESH_INVALID','用户不存在');const replacement={id:db.id(),userId:user.id,tokenHash:next.hash,expiresAt:new Date(Date.now()+config.REFRESH_TOKEN_TTL_DAYS*86400000).toISOString(),createdAt:new Date().toISOString()};current.revokedAt=new Date().toISOString();current.replacedById=replacement.id;s.refreshTokens.push(replacement);return user;});res.cookie(config.COOKIE_NAME,next.raw,{httpOnly:true,sameSite:'lax',secure:config.NODE_ENV==='production',path:'/api/v1/auth',maxAge:config.REFRESH_TOKEN_TTL_DAYS*86400000});return ok(res,{accessToken:signAccessToken({sub:user.id,username:user.username,role:user.role}),expiresIn:config.ACCESS_TOKEN_TTL_SECONDS});}));
app.post('/api/v1/auth/logout',asyncHandler(async(req,res)=>{const raw=req.cookies?.[config.COOKIE_NAME] as string|undefined;if(raw)await db.write(s=>{const token=s.refreshTokens.find(t=>t.tokenHash===hashToken(raw));if(token&&!token.revokedAt)token.revokedAt=new Date().toISOString();});res.clearCookie(config.COOKIE_NAME,{path:'/api/v1/auth'});return ok(res,{},'已退出登录');}));
app.get('/api/v1/auth/me',authenticate,asyncHandler(async(req,res)=>ok(res,dtoUser(requireItem(await db.read(s=>s.users.find(u=>u.id===req.auth!.userId)),'AUTH_TOKEN_EXPIRED','用户不存在')))));

const campaignInput=z.object({name:z.string().min(2).max(256),description:z.string().max(2000).optional(),couponType:z.string().default('fixed'),value:z.coerce.number().positive(),totalStock:z.coerce.number().int().min(1).max(100000),perUserLimit:z.coerce.number().int().min(1).max(100),startTime:z.coerce.date(),endTime:z.coerce.date(),rules:z.record(z.unknown()).optional(),metadata:z.record(z.unknown()).optional()}).refine(v=>v.endTime>v.startTime,{message:'结束时间必须晚于开始时间',path:['endTime']});
const campaignUpdate=z.object({name:z.string().min(2).max(256).optional(),description:z.string().max(2000).optional(),couponType:z.string().optional(),value:z.coerce.number().positive().optional(),totalStock:z.coerce.number().int().min(1).max(100000).optional(),perUserLimit:z.coerce.number().int().min(1).max(100).optional(),startTime:z.coerce.date().optional(),endTime:z.coerce.date().optional(),rules:z.record(z.unknown()).optional(),metadata:z.record(z.unknown()).optional()});
app.get('/api/v1/campaigns',authenticate,asyncHandler(async(req,res)=>{const q=pageSchema.extend({status:z.string().optional()}).parse(req.query),now=Date.now();const items=await db.read(s=>s.campaigns.filter(c=>req.auth!.role==='customer'?c.status==='active'&&Date.parse(c.startTime)<=now&&Date.parse(c.endTime)>now&&c.remainingStock>0:c.status!=='deleted'&&(!q.status||c.status===q.status)).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));return paginate(res,items,q);}));
app.get('/api/v1/campaigns/:id',authenticate,asyncHandler(async(req,res)=>ok(res,requireItem(await db.read(s=>s.campaigns.find(c=>c.id===req.params.id&&c.status!=='deleted')),'CAMPAIGN_NOT_FOUND','活动不存在'))));
app.post('/api/v1/campaigns',authenticate,allowRoles('operator'),asyncHandler(async(req,res)=>{const input=campaignInput.parse(req.body),now=new Date().toISOString();const item:Campaign={id:db.id(),name:input.name,description:input.description,couponType:input.couponType,value:input.value,totalStock:input.totalStock,remainingStock:input.totalStock,perUserLimit:input.perUserLimit,startTime:input.startTime.toISOString(),endTime:input.endTime.toISOString(),status:'draft',rules:input.rules??{},metadata:input.metadata??{},createdBy:req.auth!.userId,createdAt:now,updatedAt:now};await db.write(s=>s.campaigns.unshift(item));await audit(req,'campaign.create','success','campaign',item.id);return ok(res,item,'活动创建成功',201);}));
app.put('/api/v1/campaigns/:id',authenticate,allowRoles('operator'),asyncHandler(async(req,res)=>{const input=campaignUpdate.parse(req.body);const item=await db.write(s=>{const c=requireItem(s.campaigns.find(x=>x.id===req.params.id&&x.status!=='deleted'),'CAMPAIGN_NOT_FOUND','活动不存在');Object.assign(c,input,{startTime:input.startTime?.toISOString()??c.startTime,endTime:input.endTime?.toISOString()??c.endTime,updatedAt:new Date().toISOString()});if(Date.parse(c.endTime)<=Date.parse(c.startTime))throw new AppError(400,'VALIDATION_ERROR','结束时间必须晚于开始时间');return c;});await audit(req,'campaign.update','success','campaign',item.id);return ok(res,item,'活动已更新');}));
const transitions:Record<CampaignStatus,CampaignStatus[]>={draft:['active','deleted'],active:['paused','sold_out','expired','deleted'],paused:['active','expired','deleted'],sold_out:['deleted'],expired:['deleted'],deleted:[]};
app.patch('/api/v1/campaigns/:id/status',authenticate,allowRoles('operator'),asyncHandler(async(req,res)=>{const {status}=z.object({status:z.enum(['draft','active','paused','sold_out','expired','deleted'])}).parse(req.body);const item=await db.write(s=>{const c=requireItem(s.campaigns.find(x=>x.id===req.params.id),'CAMPAIGN_NOT_FOUND','活动不存在');if(!transitions[c.status].includes(status))throw new AppError(409,'CAMPAIGN_INVALID_TRANSITION','非法状态流转');c.status=status;c.updatedAt=new Date().toISOString();return c;});await audit(req,'campaign.status','success','campaign',item.id,{status});return ok(res,item);}));
app.delete('/api/v1/campaigns/:id',authenticate,allowRoles('operator'),asyncHandler(async(req,res)=>{await db.write(s=>{const c=requireItem(s.campaigns.find(x=>x.id===req.params.id&&x.status!=='deleted'),'CAMPAIGN_NOT_FOUND','活动不存在');c.status='deleted';c.updatedAt=new Date().toISOString();});await audit(req,'campaign.delete','success','campaign',String(req.params.id));return ok(res,{},'活动已删除');}));

app.post('/api/v1/campaigns/:id/claim',authenticate,allowRoles('customer'),asyncHandler(async(req,res)=>{
  const now=new Date();
  const result=await db.write(s=>{
    const campaign=requireItem(s.campaigns.find(c=>c.id===req.params.id),'CAMPAIGN_NOT_FOUND','活动不存在');
    if(campaign.remainingStock<=0||campaign.status==='sold_out')throw new AppError(409,'COUPON_OUT_OF_STOCK','优惠券已抢光');
    if(campaign.status!=='active'||Date.parse(campaign.startTime)>now.getTime()||Date.parse(campaign.endTime)<=now.getTime())throw new AppError(409,'CAMPAIGN_INACTIVE','活动当前不可领取');
    const approved=s.riskRecords.find(r=>r.userId===req.auth!.userId&&r.campaignId===campaign.id&&r.reviewStatus==='approved'&&!r.approvalConsumedAt&&r.approvalExpiresAt&&Date.parse(r.approvalExpiresAt)>now.getTime());
    const recent=s.claimRecords.filter(r=>r.userId===req.auth!.userId&&Date.parse(r.createdAt)>=now.getTime()-10000).length;
    if(!approved&&recent>=49){
      const claimId=db.id();
      s.claimRecords.push({id:claimId,campaignId:campaign.id,userId:req.auth!.userId,result:'blocked',riskScore:100,riskDecision:'block',requestId:String(req.id),createdAt:now.toISOString()});
      s.riskRecords.push({id:db.id(),claimRecordId:claimId,userId:req.auth!.userId,campaignId:campaign.id,source:'rule',riskScore:100,decision:'block',reasons:['10 秒内请求达到 50 次'],reviewStatus:'pending',createdAt:now.toISOString()});
      return{blocked:true as const};
    }
    const issued=s.claimRecords.filter(r=>r.campaignId===campaign.id&&r.userId===req.auth!.userId&&r.result==='issued').length;
    if(issued>=campaign.perUserLimit)throw new AppError(409,campaign.perUserLimit===1?'COUPON_ALREADY_CLAIMED':'COUPON_EXCEED_LIMIT',campaign.perUserLimit===1?'已领取':'已达到领取上限');
    campaign.remainingStock--;
    if(campaign.remainingStock===0)campaign.status='sold_out';
    const coupon={id:db.id(),campaignId:campaign.id,userId:req.auth!.userId,code:`CP-${Date.now().toString(36).toUpperCase()}-${randomUUID().slice(0,8).toUpperCase()}`,status:'claimed' as const,claimedAt:now.toISOString(),expiresAt:campaign.endTime,metadata:{couponType:campaign.couponType,value:campaign.value}};
    s.coupons.unshift(coupon);
    s.claimRecords.unshift({id:db.id(),campaignId:campaign.id,userId:req.auth!.userId,couponId:coupon.id,result:'issued',riskScore:approved?0:10,riskDecision:'pass',requestId:String(req.id),createdAt:now.toISOString()});
    if(approved)approved.approvalConsumedAt=now.toISOString();
    return{blocked:false as const,coupon,campaign};
  });
  if(result.blocked){
    await audit(req,'coupon.claim','blocked','campaign',String(req.params.id),{reason:'10 秒内请求达到 50 次'});
    throw new AppError(429,'RISK_BLOCKED','操作过于频繁，已被风控拦截');
  }
  await audit(req,'coupon.claim','success','coupon',result.coupon.id,{campaignId:result.campaign.id});
  return ok(res,{couponId:result.coupon.id,couponCode:result.coupon.code,campaignId:result.campaign.id,campaignName:result.campaign.name,value:result.campaign.value,expiresAt:result.coupon.expiresAt,risk:{score:10,decision:'pass',source:'rule'}},'领取成功');
}));
app.get('/api/v1/my-coupons',authenticate,allowRoles('customer'),asyncHandler(async(req,res)=>{const q=pageSchema.extend({status:z.enum(['all','usable','used','expired']).default('all')}).parse(req.query),now=Date.now();const items=await db.read(s=>s.coupons.filter(c=>c.userId===req.auth!.userId).map(c=>{const campaign=s.campaigns.find(x=>x.id===c.campaignId)!;return{id:c.id,campaignId:c.campaignId,code:c.code,status:c.status==='claimed'&&Date.parse(c.expiresAt)<=now?'expired':c.status,campaignName:campaign?.name??'未知活动',value:campaign?.value??0,claimedAt:c.claimedAt,expiresAt:c.expiresAt,verifiedAt:c.verifiedAt};}).filter(c=>q.status==='all'||q.status==='usable'&&c.status==='claimed'||q.status==='used'&&c.status==='verified'||q.status==='expired'&&c.status==='expired').sort((a,b)=>b.claimedAt.localeCompare(a.claimedAt)));return paginate(res,items,q);}));

app.post('/api/v1/verify',authenticate,allowRoles('verifier'),asyncHandler(async(req,res)=>{const input=z.object({couponCode:z.string().min(3),bizOrderNo:z.string().min(3)}).parse(req.body);const output=await db.write(s=>{const coupon=requireItem(s.coupons.find(c=>c.code===input.couponCode),'COUPON_NOT_FOUND','券码不存在');const prior=s.verifications.find(v=>v.couponId===coupon.id&&v.bizOrderNo===input.bizOrderNo);if(prior)return{...prior.responseSnapshot,idempotentReplay:true};if(Date.parse(coupon.expiresAt)<=Date.now())throw new AppError(409,'COUPON_EXPIRED','优惠券已过期');if(coupon.status!=='claimed')throw new AppError(409,'COUPON_ALREADY_VERIFIED','优惠券已核销');const verifiedAt=new Date().toISOString(),id=db.id();coupon.status='verified';coupon.verifiedAt=verifiedAt;const snapshot={verificationId:id,couponId:coupon.id,couponCode:coupon.code,bizOrderNo:input.bizOrderNo,result:'success',verifiedAt,idempotentReplay:false};s.verifications.unshift({id,couponId:coupon.id,verifierId:req.auth!.userId,bizOrderNo:input.bizOrderNo,result:'success',responseSnapshot:snapshot,createdAt:verifiedAt});return snapshot;});await audit(req,'coupon.verify','success','coupon',String((output as Record<string,unknown>).couponId),{bizOrderNo:input.bizOrderNo});return ok(res,output,output.idempotentReplay?'返回首次核销结果':'核销成功');}));
app.get('/api/v1/verifications',authenticate,allowRoles('verifier','admin'),asyncHandler(async(req,res)=>{const q=pageSchema.parse(req.query);const items=await db.read(s=>s.verifications.map(v=>{const coupon=s.coupons.find(c=>c.id===v.couponId)!,campaign=s.campaigns.find(c=>c.id===coupon?.campaignId),user=s.users.find(u=>u.id===coupon?.userId),verifier=s.users.find(u=>u.id===v.verifierId);return{id:v.id,couponCode:coupon?.code,campaignId:campaign?.id,campaignName:campaign?.name,username:user?.username,verifierName:verifier?.displayName,bizOrderNo:v.bizOrderNo,result:v.result,createdAt:v.createdAt};}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));return paginate(res,items,q);}));

app.get('/api/v1/recommendations',authenticate,allowRoles('customer'),asyncHandler(async(req,res)=>{const campaigns=await db.read(s=>s.campaigns.filter(c=>c.status==='active'&&Date.parse(c.endTime)>Date.now()&&c.remainingStock>0).sort((a,b)=>(b.totalStock-b.remainingStock)-(a.totalStock-a.remainingStock)).slice(0,3));if(!campaigns.length)return ok(res,[]);const started=Date.now();let reason='当前热门活动，库存充足，建议优先领取',source:'ai'|'rule'='rule',status='fallback',fallbackReason='Bedrock 不可用';try{const result=await bedrock.converse([{role:'user',content:`请用一句中文推荐：${campaigns.map(c=>c.name).join('、')}`}]);if(result.content.trim()){reason=result.content.trim().slice(0,200);source='ai';status='success';fallbackReason='';}}catch(error){fallbackReason=error instanceof Error?error.message:'AI error';}await db.write(s=>s.aiCallLogs.unshift({id:db.id(),requestId:req.id,userId:req.auth!.userId,purpose:'recommendation',authMode:config.BEDROCK_AUTH_MODE,modelId:config.BEDROCK_MODEL_ID,durationMs:Date.now()-started,status,fallbackReason:fallbackReason||undefined,createdAt:new Date().toISOString()}));return ok(res,campaigns.map(c=>({campaignId:c.id,campaignName:c.name,value:c.value,reason,source})));}));
app.get('/api/v1/risk/records',authenticate,allowRoles('operator','admin'),asyncHandler(async(req,res)=>{const q=pageSchema.extend({reviewStatus:z.string().optional()}).parse(req.query);const items=await db.read(s=>s.riskRecords.filter(r=>!q.reviewStatus||r.reviewStatus===q.reviewStatus).map(r=>({...r,username:s.users.find(u=>u.id===r.userId)?.username,campaignName:s.campaigns.find(c=>c.id===r.campaignId)?.name})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)));return paginate(res,items,q);}));
app.post('/api/v1/risk/records/:id/review',authenticate,allowRoles('operator'),asyncHandler(async(req,res)=>{const input=z.object({action:z.enum(['approve','reject']),comment:z.string().min(2)}).parse(req.body);const item=await db.write(s=>{const risk=requireItem(s.riskRecords.find(r=>r.id===req.params.id),'RISK_NOT_FOUND','风控记录不存在');if(risk.reviewStatus!=='pending')throw new AppError(409,'RISK_ALREADY_REVIEWED','该记录已审核');risk.reviewStatus=input.action==='approve'?'approved':'rejected';risk.reviewedBy=req.auth!.userId;risk.reviewedAt=new Date().toISOString();risk.reviewComment=input.comment;if(input.action==='approve')risk.approvalExpiresAt=new Date(Date.now()+1800000).toISOString();return risk;});await audit(req,'risk.review','success','risk_record',item.id,{action:input.action});return ok(res,item,'审核完成');}));

app.get('/api/v1/stats/overview',authenticate,allowRoles('admin'),asyncHandler(async(_req,res)=>{const stats=await db.read(s=>{const campaigns=s.campaigns.filter(c=>c.status!=='deleted'),totalStock=campaigns.reduce((n,c)=>n+c.totalStock,0),totalClaims=s.claimRecords.filter(c=>c.result==='issued').length,totalVerifications=s.verifications.filter(v=>v.result==='success').length;return{totalCampaigns:campaigns.length,totalClaims,totalVerifications,claimRate:totalStock?totalClaims/totalStock*100:0,verificationRate:totalClaims?totalVerifications/totalClaims*100:0,remainingStock:campaigns.reduce((n,c)=>n+c.remainingStock,0),trends:[],statusDistribution:Object.entries(campaigns.reduce<Record<string,number>>((a,c)=>(a[c.status]=(a[c.status]??0)+1,a),{})).map(([status,count])=>({status,count})),recentRisks:s.riskRecords.slice(0,5)};});return ok(res,stats);}));
app.get('/api/v1/stats/campaigns/:id',authenticate,allowRoles('operator','admin'),asyncHandler(async(req,res)=>{const stats=await db.read(s=>{const campaign=requireItem(s.campaigns.find(c=>c.id===req.params.id),'CAMPAIGN_NOT_FOUND','活动不存在'),claims=s.claimRecords.filter(c=>c.campaignId===campaign.id&&c.result==='issued').length,verifications=s.verifications.filter(v=>s.coupons.find(c=>c.id===v.couponId)?.campaignId===campaign.id).length;return{campaign,claims,verifications,claimRate:campaign.totalStock?claims/campaign.totalStock*100:0,verificationRate:claims?verifications/claims*100:0};});return ok(res,stats);}));
app.get('/api/v1/admin/audit-logs',authenticate,allowRoles('admin'),asyncHandler(async(req,res)=>{const q=pageSchema.extend({action:z.string().optional(),outcome:z.string().optional(),resourceType:z.string().optional()}).parse(req.query);const items=await db.read(s=>s.auditLogs.filter(a=>(!q.action||a.action===q.action)&&(!q.outcome||a.outcome===q.outcome)&&(!q.resourceType||a.resourceType===q.resourceType)).map(a=>({...a,actorName:s.users.find(u=>u.id===a.actorId)?.displayName})));return paginate(res,items,q);}));

app.use(notFoundHandler);app.use(errorHandler);export{app};
